# Generated by Django 3.2.8 on 2021-10-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modes',
            old_name='modes',
            new_name='mode',
        ),
    ]
