# Generated by Django 4.0.5 on 2022-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GardenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=20, verbose_name='Type')),
                ('p_variety', models.CharField(max_length=20, verbose_name='Variety')),
                ('p_planting_date', models.DateField(verbose_name='Planting (date)')),
                ('p_location', models.JSONField(verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=20, verbose_name='Type')),
                ('p_variety', models.CharField(max_length=20, verbose_name='Variety')),
                ('p_num_of_seeds_in_1g', models.PositiveIntegerField(verbose_name='Number of seeds in 1g')),
                ('p_planting_date', models.JSONField(verbose_name='Planting (month)')),
                ('p_planting_temp', models.JSONField(verbose_name='Planting temperature (°C)')),
                ('p_planting_depth', models.JSONField(verbose_name='Planting depth (cm)')),
                ('p_germination_time', models.JSONField(verbose_name='Germination (days)')),
                ('p_harvest_time', models.JSONField(verbose_name='Harvest (days)')),
                ('p_harvest_date', models.JSONField(verbose_name='Harvest (month)')),
                ('p_length_of_root', models.JSONField(verbose_name='Length of root (cm)')),
                ('p_diameter', models.JSONField(verbose_name='Diameter (cm)')),
                ('p_watering_time', models.TimeField(verbose_name='Watering (duration)')),
                ('p_class', models.CharField(max_length=20, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedMode', models.CharField(max_length=20, verbose_name='Selected mode')),
                ('refreshInterval', models.PositiveIntegerField(default=1000, verbose_name='Refresh interval')),
            ],
        ),
        migrations.CreateModel(
            name='WateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
            ],
        ),
    ]
